### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/libretranslate_ynh#10]
### Context

- Hardware: *VPS bought online *
- YunoHost version: 11.1.19 (stable).
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

You can see the full log here https://paste.yunohost.org/raw/olerosacav 

```
023-05-14 13:34:30,445: DEBUG - ✘ Failed creating virtual environment
2023-05-14 13:34:30,445: DEBUG - [pipenv.exceptions.VirtualenvCreationException]:
2023-05-14 13:34:30,446: DEBUG - Failed to create virtual environment.
2023-05-14 13:34:30,632: DEBUG - + ynh_exit_properly
2023-05-14 13:34:30,632: DEBUG - + [[ install =~ ^install$|^upgrade$|^restore$ ]]
2023-05-14 13:34:32,139: ERROR - Unable to install libretranslate: An error occurred inside the app installation script
```

**Comment by tio-trom** [comment]
1.3.11 also fails - https://paste.yunohost.org/raw/unepuzegud

**Comment by ericgaspar** [comment]
not related but there is a new translator in the catalog
https://github.com/YunoHost-Apps/lingva_ynh

**Comment by Thovi98** [comment]
Could you please try via ssh `apt remove python3-virtualenv` and retry installation?

**Comment by tio-trom** [comment]
> not related but there is a new translator in the catalog https://github.com/YunoHost-Apps/lingva_ynh

I know but that's an interface for google translate. I'd love to use LibreTranslate since that is an open source translation engine. An alternative to google and the rest.



> Could you please try via ssh `apt remove python3-virtualenv` and retry installation?

I will tomorrow, thanks. Hopefully it won't mess up with the other services I have installed (some 20+ ynh services on the same server).

**Comment by Thovi98** [comment]
Before uninstalling, verify which packages it will remove :)
For example, see this : https://github.com/YunoHost-Apps/fittrackee_ynh/issues/22#issuecomment-1574350666. Some apps may not (yet) be compatible

**Comment by tio-trom** [comment]
I get this:

```
The following packages were automatically installed and are no longer required:
  libacl1-dev libattr1-dev libfuse-dev liblz4-dev libpcre2-16-0 libpcre2-32-0
  libpcre2-dev libpcre2-posix3 libselinux1-dev libsepol1-dev python3-distlib
  python3-filelock python3-importlib-metadata python3-more-itertools
  python3-zipp
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  borg-ynh-deps python3-virtualenv virtualenv
0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
```

I am unsure if I need any of those packages?

**Comment by tio-trom** [comment]
Worked! I hope `borg-ynh-deps python3-virtualenv virtualenv` were not needed.

**Comment by Thovi98** [comment]
Mmmh I hope you didn't need borg anymore?

**Comment by tio-trom** [comment]
> Mmmh I hope you didn't need borg anymore?

Borg still looks as it is installed. And why would it conflict with Libretranslate? Meaning `python3-virtualenv`
