### ISSUE TITLE
Install problem: Current version 1.3.11~ynh2

### ISSUE THREAD

**Issue by mateMathieu** [YunoHost-Apps/libretranslate_ynh#16]
Hi, I the following log when I try to install on a sub-domain:

- Hardware: computer x64
- YunoHost version: last stable update branch (*11.2.3*)
- I have access to my server: *through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Logs
https://paste.yunohost.org/raw/ayabawiyoq

**Comment by mateMathieu** [comment]
Reference to previous bug:
I need borg and a python3-env on this instance of ynh. 
Thanks

**Comment by Thovi98** [comment]
> I need borg and a python3-env on this instance of ynh.

I've changed the way LibreTranslate installs so it's now compatible.

Following your logs:
`ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device`

So I would look in that direction :)
