### ISSUE TITLE
status of this app

### ISSUE THREAD

**Issue by mooseyboots** [YunoHost-Apps/libretranslate_ynh#4]
hey, what is the current status of this app?

can i manually get it install on my ynh? happy to test it out, if poss to do so.

**Comment by Thovi98** [comment]
If you want to test it out, you can, by executing 
`sudo yunohost app install https://github.com/YunoHost-Apps/libretranslate_ynh/tree/testing --debug`

But as you can see in https://github.com/YunoHost-Apps/libretranslate_ynh/pull/1, the app is not ready yet, so expect bugs at installation/upgrade/running the app
